# SPDX-License-Identifier: MIT

name: Test Suite

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  codestyle:
    name: Format & Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Check formatting
        run: uvx ruff format --check .

      - name: Check
        run: uvx ruff check .

  tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Sync
        run: uv sync --all-extras --dev

      - name: Run tests
        run: uv run pytest .
